# Generated by Django 5.1.2 on 2024-12-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="signature",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Firma de integridad",
            ),
        ),
    ]
