# Generated by Django 5.1.2 on 2024-12-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_transaction_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("RECHARGE", "Recarga"), ("PAYMENT", "Pago")],
                default="RECHARGE",
                max_length=20,
                verbose_name="Tipo de transacción",
            ),
        ),
    ]
