# Generated by Django 5.1.2 on 2025-02-10 10:35

import apps.payments.models.withdrawal
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_transaction_transaction_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankDestinationAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "bank",
                    models.CharField(
                        choices=[
                            ("BANCOLOMBIA", "Bancolombia"),
                            ("BANCO_BOGOTA", "Banco de Bogotá"),
                            ("DAVIVIENDA", "Davivienda"),
                            ("BBVA", "BBVA Colombia"),
                            ("OCCIDENTE", "Banco de Occidente"),
                            ("POPULAR", "Banco Popular"),
                            ("AVVILLAS", "Banco AV Villas"),
                            ("CAJA_SOCIAL", "Banco Caja Social"),
                            ("ITAU", "Itaú"),
                            ("SCOTIABANK", "Scotiabank Colpatria"),
                            ("FALABELLA", "Banco Falabella"),
                            ("PICHINCHA", "Banco Pichincha"),
                            ("BANCAMIA", "Bancamía"),
                            ("BANCOW", "Banco W"),
                            ("COOPCENTRAL", "Banco Coopcentral"),
                            ("FINANDINA", "Banco Finandina"),
                            ("SANTANDER", "Banco Santander"),
                            ("AGRARIO", "Banco Agrario"),
                            ("NEQUI", "Nequi"),
                            ("DAVIPLATA", "Daviplata"),
                            ("DALE", "Dale"),
                            ("MOVII", "Movii"),
                            ("RAPPIPAY", "RappiPay"),
                            ("IRIS", "Iris"),
                            ("TPAGA", "Tpaga"),
                            ("LULO", "Lulo Bank"),
                            ("NU_BANK", "Nu Bank"),
                            ("CONFIAR", "Confiar Cooperativa Financiera"),
                            ("COOFINEP", "Coofinep"),
                            ("COTRAFA", "Cotrafa"),
                            ("JFK", "Cooperativa Financiera JFK"),
                        ],
                        max_length=50,
                        verbose_name="Banco",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("SAVINGS", "Cuenta de Ahorros"),
                            ("CHECKING", "Cuenta Corriente"),
                            ("DIGITAL", "Cuenta Digital"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de cuenta",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(max_length=30, verbose_name="Número de cuenta"),
                ),
                (
                    "account_owner",
                    models.CharField(
                        max_length=200, verbose_name="Titular de la cuenta"
                    ),
                ),
                (
                    "identification_type",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("NIT", "NIT"),
                            ("PP", "Pasaporte"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de identificación",
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(
                        max_length=20, verbose_name="Número de identificación"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "description",
                    models.CharField(
                        help_text="Descripción para identificar la cuenta (ej: Cuenta principal premios)",
                        max_length=200,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta bancaria destino",
                "verbose_name_plural": "Cuentas bancarias destino",
                "ordering": ["bank", "-is_active"],
            },
        ),
        migrations.CreateModel(
            name="PrizeWithdrawal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000000),
                        ],
                        verbose_name="Monto",
                    ),
                ),
                (
                    "withdrawal_code",
                    models.CharField(
                        default=apps.payments.models.withdrawal.generate_withdrawal_code,
                        max_length=10,
                        unique=True,
                        verbose_name="Código de retiro",
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        choices=[
                            ("BANCOLOMBIA", "Bancolombia"),
                            ("BANCO_BOGOTA", "Banco de Bogotá"),
                            ("DAVIVIENDA", "Davivienda"),
                            ("BBVA", "BBVA Colombia"),
                            ("OCCIDENTE", "Banco de Occidente"),
                            ("POPULAR", "Banco Popular"),
                            ("AVVILLAS", "Banco AV Villas"),
                            ("CAJA_SOCIAL", "Banco Caja Social"),
                            ("ITAU", "Itaú"),
                            ("SCOTIABANK", "Scotiabank Colpatria"),
                            ("FALABELLA", "Banco Falabella"),
                            ("PICHINCHA", "Banco Pichincha"),
                            ("BANCAMIA", "Bancamía"),
                            ("BANCOW", "Banco W"),
                            ("COOPCENTRAL", "Banco Coopcentral"),
                            ("FINANDINA", "Banco Finandina"),
                            ("SANTANDER", "Banco Santander"),
                            ("AGRARIO", "Banco Agrario"),
                            ("NEQUI", "Nequi"),
                            ("DAVIPLATA", "Daviplata"),
                            ("DALE", "Dale"),
                            ("MOVII", "Movii"),
                            ("RAPPIPAY", "RappiPay"),
                            ("IRIS", "Iris"),
                            ("TPAGA", "Tpaga"),
                            ("LULO", "Lulo Bank"),
                            ("NU_BANK", "Nu Bank"),
                            ("CONFIAR", "Confiar Cooperativa Financiera"),
                            ("COOFINEP", "Coofinep"),
                            ("COTRAFA", "Cotrafa"),
                            ("JFK", "Cooperativa Financiera JFK"),
                        ],
                        max_length=50,
                        verbose_name="Banco",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("SAVINGS", "Cuenta de Ahorros"),
                            ("CHECKING", "Cuenta Corriente"),
                            ("DIGITAL", "Cuenta Digital"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de cuenta",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(max_length=30, verbose_name="Número de cuenta"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("APPROVED", "Aprobado"),
                            ("REJECTED", "Rechazado"),
                            ("EXPIRED", "Expirado"),
                            ("REVERSED", "Reversado"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de expiración"
                    ),
                ),
                (
                    "processed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de procesamiento"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, verbose_name="Notas del administrador"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_account",
                    models.ForeignKey(
                        help_text="Cuenta bancaria donde se enviará el premio",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.bankdestinationaccount",
                        verbose_name="Cuenta destino",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prize_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retiro de premio",
                "verbose_name_plural": "Retiros de premios",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["withdrawal_code"],
                        name="payments_pr_withdra_279849_idx",
                    ),
                    models.Index(
                        fields=["status"], name="payments_pr_status_e19ad2_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="payments_pr_created_f24d6d_idx"
                    ),
                    models.Index(
                        fields=["user", "status"], name="payments_pr_user_id_95abe1_idx"
                    ),
                ],
            },
        ),
    ]
