# Generated by Django 5.1.2 on 2025-03-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_bankdestinationaccount_prizewithdrawal"),
    ]

    operations = [
        migrations.AddField(
            model_name="prizewithdrawal",
            name="use_keys",
            field=models.BooleanField(
                default=False,
                help_text="Indica si se utilizará el sistema de llaves para realizar el pago",
                verbose_name="Utilizar llaves para pago",
            ),
        ),
    ]
