# Generated by Django 5.1.2 on 2024-12-07 23:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lottery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                (
                    "draw_day",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Lunes"),
                            ("TUESDAY", "Martes"),
                            ("WEDNESDAY", "Miércoles"),
                            ("THURSDAY", "Jueves"),
                            ("FRIDAY", "Viernes"),
                            ("SATURDAY", "Sábado"),
                        ],
                        max_length=10,
                        verbose_name="Día de sorteo",
                    ),
                ),
                ("draw_time", models.TimeField(verbose_name="Hora del sorteo")),
                (
                    "fraction_count",
                    models.PositiveIntegerField(verbose_name="Cantidad de fracciones"),
                ),
                (
                    "fraction_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio fracción"
                    ),
                ),
                (
                    "major_prize_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Premio mayor"
                    ),
                ),
                (
                    "min_bet_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Apuesta mínima",
                    ),
                ),
                (
                    "max_bet_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Apuesta máxima",
                    ),
                ),
                ("logo_url", models.URLField(blank=True, verbose_name="Logo URL")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "requires_series",
                    models.BooleanField(default=True, verbose_name="Requiere serie"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lotería",
                "verbose_name_plural": "Loterías",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Bet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "number",
                    models.CharField(
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{4}$", "Debe ser un número de 4 dígitos"
                            )
                        ],
                        verbose_name="Número",
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Serie"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Monto apostado",
                    ),
                ),
                ("draw_date", models.DateField(verbose_name="Fecha del sorteo")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PLAYED", "Jugada"),
                            ("WON", "Ganadora"),
                            ("LOST", "Perdedora"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "won_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Monto ganado",
                    ),
                ),
                (
                    "winning_details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Detalles de premio"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lottery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bets",
                        to="lottery.lottery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apuesta",
                "verbose_name_plural": "Apuestas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrizePlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=150, verbose_name="Nombre")),
                ("start_date", models.DateField(verbose_name="Fecha inicio")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha fin"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "sorteo_number",
                    models.CharField(
                        blank=True,
                        help_text="Ej: 2720",
                        max_length=20,
                        verbose_name="Número de sorteo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lottery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prize_plans",
                        to="lottery.lottery",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de premios",
                "verbose_name_plural": "Planes de premios",
            },
        ),
        migrations.CreateModel(
            name="PrizeType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "match_rules",
                    models.JSONField(
                        default=dict,
                        help_text='Reglas para validar coincidencias {"type": "exact", "positions": [0,1,2,3]}',
                        verbose_name="Reglas de coincidencia",
                    ),
                ),
                (
                    "requires_series",
                    models.BooleanField(default=False, verbose_name="Requiere serie"),
                ),
                (
                    "requires_exact_match",
                    models.BooleanField(
                        default=True, verbose_name="Coincidencia exacta"
                    ),
                ),
                (
                    "is_special",
                    models.BooleanField(default=False, verbose_name="Premio especial"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de premio",
                "verbose_name_plural": "Tipos de premios",
            },
        ),
        migrations.CreateModel(
            name="Prize",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Monto"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Número de premios de este tipo",
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "fraction_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        verbose_name="Monto por fracción",
                    ),
                ),
                (
                    "custom_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Reglas específicas para este premio",
                        verbose_name="Reglas personalizadas",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text='Para premios especiales como "Sueldazo cafetero"',
                        max_length=100,
                        verbose_name="Nombre personalizado",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prize_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prizes",
                        to="lottery.prizeplan",
                    ),
                ),
                (
                    "prize_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prizes",
                        to="lottery.prizetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Premio",
                "verbose_name_plural": "Premios",
                "ordering": ["order", "id"],
            },
        ),
    ]
