# Generated by Django 5.1.2 on 2024-12-15 21:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0003_alter_lottery_fraction_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lottery",
            name="number_ranges_file",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Archivo de rangos"
            ),
        ),
        migrations.AddField(
            model_name="lottery",
            name="unsold_tickets_file",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Archivo de billetes no vendidos",
            ),
        ),
    ]
