# Generated by Django 5.1.2 on 2024-12-15 21:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0004_lottery_number_ranges_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lottery",
            name="sales_file",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Archivo de ventas"
            ),
        ),
    ]
