# Generated by Django 5.1.4 on 2024-12-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0006_alter_prizeplan_options_lottery_closing_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lottery",
            name="series",
            field=models.CharField(
                blank=True,
                help_text="Series de la lotería separadas por comas",
                max_length=255,
                verbose_name="Series",
            ),
        ),
    ]
