# Generated by Django 5.1.2 on 2024-12-28 14:15

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0007_lottery_available_series"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="series",
            field=models.CharField(
                default=1,
                max_length=3,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{3}$", "Debe ser una serie de 3 dígitos"
                    )
                ],
                verbose_name="Serie",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="bet",
            constraint=models.UniqueConstraint(
                fields=("lottery", "series", "draw_date"),
                name="unique_lottery_series_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="bet",
            constraint=models.UniqueConstraint(
                fields=("lottery", "number", "draw_date"),
                name="unique_lottery_number_date",
            ),
        ),
    ]
