# Generated by Django 5.1.2 on 2024-12-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0008_alter_bet_series_bet_unique_lottery_series_date_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bet",
            name="unique_lottery_series_date",
        ),
    ]
