# Generated by Django 5.1.2 on 2024-12-28 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0009_remove_bet_unique_lottery_series_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bet",
            name="unique_lottery_number_date",
        ),
        migrations.AddConstraint(
            model_name="bet",
            constraint=models.UniqueConstraint(
                fields=("lottery", "number"), name="unique_lottery_number_date"
            ),
        ),
    ]
