# Generated by Django 5.1.2 on 2025-01-14 18:29

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0011_lottery_allow_duplicate_numbers_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bet",
            name="unique_lottery_number_date",
        ),
        migrations.AddField(
            model_name="lottery",
            name="series",
            field=models.CharField(
                default="000",
                max_length=3,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{3}$", "Debe ser una serie de 3 dígitos"
                    )
                ],
                verbose_name="Serie por defecto",
            ),
        ),
        migrations.AddConstraint(
            model_name="bet",
            constraint=models.UniqueConstraint(
                fields=("lottery", "number", "series", "draw_date"),
                name="unique_lottery_number_series_date",
            ),
        ),
    ]
