# Generated by Django 5.1.2 on 2025-01-15 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0013_alter_lottery_series"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lottery",
            name="max_fractions_per_combination",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Máximo de fracciones que un usuario puede comprar por combinación número-serie",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Máximo fracciones por combinación",
            ),
        ),
    ]
