# Generated by Django 5.1.2 on 2025-02-12 10:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0014_alter_lottery_max_fractions_per_combination"),
    ]

    operations = [
        migrations.CreateModel(
            name="LotteryNumberCombination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{4}$", "Debe ser un número de 4 dígitos"
                            )
                        ],
                        verbose_name="Número",
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{3}$", "Debe ser una serie de 3 dígitos"
                            )
                        ],
                        verbose_name="Serie",
                    ),
                ),
                (
                    "total_fractions",
                    models.PositiveIntegerField(
                        help_text="Número total de fracciones disponibles",
                        verbose_name="Total de fracciones",
                    ),
                ),
                (
                    "used_fractions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Fracciones usadas"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "draw_date",
                    models.DateField(null=True, verbose_name="Fecha del sorteo"),
                ),
                (
                    "lottery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valid_combinations",
                        to="lottery.lottery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Combinación de Lotería",
                "verbose_name_plural": "Combinaciones de Lotería",
                "indexes": [
                    models.Index(
                        fields=["lottery", "number", "series"],
                        name="lottery_lot_lottery_e1638c_idx",
                    ),
                    models.Index(
                        fields=["draw_date"], name="lottery_lot_draw_da_2f712c_idx"
                    ),
                ],
                "unique_together": {("lottery", "number", "series", "draw_date")},
            },
        ),
    ]
