# Generated by Django 5.1.2 on 2025-02-14 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0015_lotterynumbercombination"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lottery",
            name="max_fractions_per_combination",
        ),
        migrations.AddField(
            model_name="lottery",
            name="max_fractions_per_bet",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Máximo de fracciones que un usuario puede comprar en una sola apuesta. No puede ser mayor que el total de fracciones del billete.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Máximo fracciones por apuesta",
            ),
            preserve_default=False,
        ),
    ]
