# Generated by Django 5.1.2 on 2025-02-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0016_remove_lottery_max_fractions_per_combination_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bet",
            name="unique_lottery_number_series_date",
        ),
    ]
