# Generated by Django 5.1.2 on 2025-02-14 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0017_remove_bet_unique_lottery_number_series_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="fractions",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Cantidad de fracciones",
            ),
        ),
    ]
