# Generated by Django 5.1.2 on 2025-03-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0018_bet_fractions"),
    ]

    operations = [
        migrations.AddField(
            model_name="lottery",
            name="valid_combinations_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Combinaciones serie-número válidas para esta lotería",
                verbose_name="Combinaciones válidas",
            ),
        ),
    ]
