# Generated by Django 5.1.2 on 2025-03-15 21:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0019_lottery_valid_combinations_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="lottery",
            name="combinations_file",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Archivo CSV con combinaciones de números y series",
                max_length=255,
                null=True,
                verbose_name="Archivo de combinaciones",
            ),
        ),
    ]
