# Generated by Django 5.1.2 on 2025-03-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0020_lottery_combinations_file"),
    ]

    operations = [
        # Eliminamos la operación para is_winner
        # migrations.AddField(
        #     model_name="lotterynumbercombination",
        #     name="is_winner",
        #     field=models.BooleanField(
        #         default=False,
        #         help_text="Indica si esta combinación resultó ganadora en el sorteo",
        #         verbose_name="Es ganadora",
        #     ),
        # ),
        migrations.AddField(
            model_name="lotterynumbercombination",
            name="prize_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monto del premio ganado si esta combinación es ganadora",
                max_digits=15,
                null=True,
                verbose_name="Monto del premio",
            ),
        ),
        migrations.AddField(
            model_name="lotterynumbercombination",
            name="prize_detail",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Información detallada del premio ganado",
                null=True,
                verbose_name="Detalle del premio",
            ),
        ),
        # migrations.AddField(
        #     model_name="lotterynumbercombination",
        #     name="prize_type",
        #     field=models.CharField(
        #         blank=True,
        #         help_text="Tipo de premio ganado (Mayor, Seco, Aproximación, etc.)",
        #         max_length=50,
        #         null=True,
        #         verbose_name="Tipo de premio",
        #     ),
        # ),
        # También eliminamos la operación para añadir el índice
        # migrations.AddIndex(
        #     model_name="lotterynumbercombination",
        #     index=models.Index(
        #         fields=["is_winner"], name="lottery_lot_is_winn_64e37f_idx"
        #     ),
        # ),
    ]
