# Generated by Django 5.1.2 on 2025-03-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0021_lotterynumbercombination_is_winner_and_more"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="lotterynumbercombination",
        #     name="is_winner",
        #     field=models.BooleanField(
        #         default=False,
        #         help_text="Indica si esta combinación resultó ganadora en el sorteo",
        #         verbose_name="Es ganadora",
        #     ),
        # ),
        # migrations.AddField(
        #     model_name="lotterynumbercombination",
        #     name="prize_type",
        #     field=models.CharField(
        #         blank=True,
        #         help_text="Tipo de premio ganado (Mayor, Seco, Aproximación, etc.)",
        #         max_length=50,
        #         null=True,
        #         verbose_name="Tipo de premio",
        #     ),
        # ),
        migrations.AlterField(
            model_name="lottery",
            name="valid_combinations_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Combinaciones serie-número válidas para esta lotería",
                null=True,
                verbose_name="Combinaciones válidas",
            ),
        ),
        # migrations.AddIndex(
        #     model_name="lotterynumbercombination",
        #     index=models.Index(
        #         fields=["is_winner"], name="lottery_lot_is_winn_64e37f_idx"
        #     ),
        # ),
    ]
