# Generated by Django 5.1.2 on 2025-03-16 20:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0023_remove_lottery_valid_combinations_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lottery",
            name="prize_plan_file",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Archivo PDF o imagen del plan de premios actual",
                max_length=255,
                null=True,
                verbose_name="Archivo de plan de premios",
            ),
        ),
        # migrations.AddField(
        #     model_name="lotterynumbercombination",
        #     name="is_winner",
        #     field=models.BooleanField(
        #         default=False,
        #         help_text="Indica si esta combinación resultó ganadora en el sorteo",
        #         verbose_name="Es ganadora",
        #     ),
        # ),
        # migrations.AddField(
        #     model_name="lotterynumbercombination",
        #     name="prize_type",
        #     field=models.CharField(
        #         blank=True,
        #         help_text="Tipo de premio ganado (Mayor, Seco, Aproximación, etc.)",
        #         max_length=50,
        #         null=True,
        #         verbose_name="Tipo de premio",
        #     ),
        # ),
        # migrations.AddIndex(
        #     model_name="lotterynumbercombination",
        #     index=models.Index(
        #         fields=["is_winner"], name="lottery_lot_is_winn_64e37f_idx"
        #     ),
        # ),
    ]
